[connections.gsheets]
type = "gspread"
spreadsheet = "https://docs.google.com/spreadsheets/d/16w1teA8YAUrAGSIGHaB0yDuPzN0OhQdoBMqn-hJmPV0/edit?gid=0#gid=0"

[connections.gsheets.service_account]
type = "service_account"
project_id = "handy-buttress-495410-r6"
private_key_id = "035e0f786f5bbc2abe2d58d69e4ff5a062e43ee0"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuU+LrFoV7BbUb\nZBbM0nRgLRayVY2LC8WpKdZPowPyP7YrLfxpDMtCMnpMDMjmLggY2eNq0Ye2H2OW\nYb2rEkw7iS5l0EmIbV7bpWvPqnoiByRqn1FcGJX+y84wzsK0Bt4aBoA4jJu2qyUG\nOXj+/9PoyipwSBmU1g/BCA9p/duPfCoTcG/OchunWYng/DNFfyyjGHMT+DQAeLf1\nCgBhx9bdkDZBtnrYl5kFLWqj7QNkJmB6b3598xLjW7KZC1gYruWuWKoBT5V38k+7\n9CoqP8HCGosVSiumsnQRn0DPd+PaMUXQivs9596oMZvUitGQcKbAirjOTaQIYiHZ\nTcFuyDGJAgMBAAECggEAJgoG925cJQqLSNVPxlTb8QqVq8dQUfl5IZ8P9SOonkk5\nunVX4SJaDfFOz15wzg1YVffhkHL1Lo/t3qgoR3aALPOTrMLE8OCQtNQFUPStntQ5\nJYzrJ3Hz9PvK28qaIMdo2nv1qaFA7xysQQ30cYwoVOEcXpDVCC2nlWLpXiL3MHk2\nqTHwxglWJlw4zHU0R/NnSJTd/Rp3JmQUWwZ4E3mjjQrG9HTp67dW1QO1zCyf5DJd\noGugaVeT/BTR836UW+nEwj/8Dx+hWemRFnrIyazt3NIT8EAQ6An7kPFnm13DzaOP\nTR/onamovcFt29oqlgKIQVbZq5X+A6sWP4NEphwJkwKBgQDf9LJPp6Og0e4dU4zM\n+S+emNGVOF3OIZljCCrrVxpVLNuZuBrkN0m7xCFUKIX45fVJ2/JpMM7s6m4tEbly\n6ulP8yEdruo+Q+8pWcH+BiMy+Acw7UIwQy/BgJyLO56H1eN2sYygKElv+CvfYPqz\n2D6ObfqRhaHrM3xcCiO3ZjII6wKBgQDHRVq12BeBavrSKHPxOogDC2AEVmq/pigL\nCPrYdtETjFd88jnwJOJfv96Toh/xsZLFWalv5rfWrMmTKfRIOASjxlILtPCox4fl\n9txttLc8GRW15UI0JwO2KDKvMNjmYQbt4/EaujWDeQRfot39FPxgfFNJzI6V5yoI\nUgPFm3uSWwKBgQCRCpzg0aU7Zjpca9vodAnPIRG7HoJCGaiJZqTFPegj+aVPbNid\nrODn5iHfq07435V4fCYG0kFxVnJ8ZdpA/rqTuNZdrwatxLmDgkoNBlSNkey2VzJi\np2CqZWz9D2OgfXmPSXXV08Gb7pIbXWeASjBZdgitbmprNTD5OufewyTseQKBgAML\nKySF5W4DnUsidQrlMvig7tmCHGVK+2eXvoUZ432h8iAlbv8dARwnSRYGLui5Jp2/\nDdh4tKwhvX5y8Jk9ycxalhw5qkdZrNi1WY6PaREQ7QT3OHilc+gPWx7T5yw1pS5z\nAda/q1uTuJ5hVXStImGy5G7HIhJmEn1IC2i0REHrAoGBAIOY+swFNS9v4r7JtVxS\n1V2VxnaGkz55V6BKDd7ydbVYuUz9rPzgaMUw+Qt1nV8WwW+4F3F8bISLaaTbvZsv\nUo2YkT6rbN3xPHy3RR85rp2ZkDvxrMmla0jaFZM+cA4fwTh47VRTJS+BylWkVnYe\nuW2cTToWjzYOseFszjhgZCg/\n-----END PRIVATE KEY-----\n"
client_email = "easyvocab@handy-buttress-495410-r6.iam.gserviceaccount.com"
client_id = "109479745227140493178"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/easyvocab%40handy-buttress-495410-r6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[admin]
password = "2299"

[ai]
gemini_api_key = "AIzaSyC0Pgm0D8bo-XU03whfmPJMMii8YuUtuyA"
model = "gemini-1.5-flash"
